config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'books/list'
  get 'books/new'
  post 'books/create'
  patch 'books/update'
  get 'books/list'
  get 'books/show'
  get 'books/edit'
  get 'books/delete'
  get 'books/update'
  get 'books/show_subjects'

  get 'subjects/list'
  get 'subjects/new'
  post 'subjects/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :subject
  validates_presence_of :title, :url
  validates_numericality_of :price, message: 'Error Message'
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :books
    validates_presence_of :name, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def list
    @books = Book.all
    @subjects = Subject.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @subjects = Subject.all
  end

  def book_params
    params.require(:book).permit(:title, :price, :subject_id, :description, :url)
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to action: 'list'
    else
      @subjects = Subject.all
      render action: 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @subjects = Subject.all
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to action: 'show', id: @book
    else
      @subjects = Subject.all
      render action: 'edit'
    end
  end

  def delete
    @book = Book.find(params[:id]).destroy
    redirect_to action: 'list'
  end

  def show_subjects
    @subject = Subject.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def new
    @subject = Subject.new
  end

  def list
    @subjects = Subject.all
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to action: 'list'
    else
      render action: 'new'
    end
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/books/edit.html.erb
<div class="container-fluid p-5">
  <h1 class="mb-3">Edit Book Detail</h1>


  <div class="d-flex gap-5 align-items-center">

  <div>
    <div style="width:400px;">
      <%= form_with(model: @book, url: "http://localhost:3000/books/update?id=#{@book.id}", method: :patch) do |form| %>
        <div class="mb-3">
          <%= form.label :title, 'Title: ', class: "form-label"%>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :url, 'Image URL: ', class: "form-label"%>
          <%= form.text_field :url, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :price, 'Price: ', class: "form-label" %>
          <%= form.text_field :price, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :subject_id, 'Subject: ', class: "form-label" %>
          <%= form.collection_select :subject_id, @subjects, :id, :name, prompt: true%>
        </div>

        <div class="mb-3">
          <%= form.label :description, 'Description', class: "form-label"%>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <%= form.submit "Save Changes", class: "btn btn-primary", style: "width: 100%;" %>
      <% end %>
    </div>

  </div>

  <div>
    <img src="https://www.shareicon.net/data/2015/08/15/85592_upload_512x512.png" style="width:200px; height:auto; object-fit:cover;">
  </div>

</div>

<p class="mt-5">
  Go Back: 
  <%= link_to ' Click me', books_list_path %>
</p>

app/views/books/list.html.erb
<!-- Banner Image -->
<div class="container-fluid d-flex align-items-start justify-content-center" 
    style="
        height: calc(100vh - 50px);
        background: url('https://img.freepik.com/free-photo/creative-world-book-day-composition_23-2148883779.jpg?w=1380&t=st=1703235933~exp=1703236533~hmac=972b401d8c35af9e6894ab5938a59ac92d79921e62a0d1e865ca3ea4a175ef15');
        background-repeat: no-repeat;
        background-size: cover;"
    >
    <div class="px-5 py-3" style="background: #FFF; opacity: 0.9; margin-top: 200px;">
        <p style="font-size: 100px;">Book List</p>
    </div>
</div>
<!-- Banner Image -->

<div class="mt-5 px-5 container-fluid">
    <div>
        <div class='d-flex justify-content-between align-items-center'>
            <h2> Subjects: </h2>
            <%= link_to 'Add Subject' , subjects_new_path, class: " btn btn-primary text-decoration-none" %>
        </div>

        <div class='d-flex gap-5 mb-5 flex-wrap mt-3'>
            <% @subjects.each do |subject|%>
                <div class="card" style="width: 10rem;">
                    <img src="<%= subject.url%>" style="height:200px; object-fit:cover;" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to subject.name, "http://localhost:3000/books/show_subjects?id=#{subject.id}", class: "text-decoration-none"  %>
                        </h5>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <div>
        <div class='d-flex justify-content-between align-items-center'>
            <h2> Books: </h2>
            <%= link_to 'Add Book' , books_new_path, class: " btn btn-primary text-decoration-none" %>
        </div>

        <div class='d-flex gap-5 mb-5 flex-wrap mt-3'>
            <% @books.each do |book|%>

                <div class="card" style="width: 15rem;">
                    <img src="<%= book.url%>" style="height:350px; object-fit:cover;" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to book.title, {action: "show", id: book.id}, class: "text-decoration-none"%>
                        </h5>
                        <p class="card-text">
                            <%= book.description%>
                        </p>
                        <div class="d-flex gap-2 justify-content-between mt-2 px-1">
                            <%= link_to 'Edit' , {action: 'edit', id: book.id}, class: "btn btn-primary" %>
                            <%= link_to 'Delete' , {action: 'delete', id: book.id}, class: "btn btn-danger text-decoration-none" %>
                        </div>
                    </div>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/books/new.html.erb
<div class="container-fluid p-5">
  <h2 class="mb-3">Add new Book</h2>


  <div class="d-flex gap-5 align-items-center">

  <div>
    <div style="width:400px;">
      <%= form_with(model: @book, url: books_create_path) do |form| %>
        <div class="mb-3">
          <%= form.label :title, 'Title', class: "form-label"%>: 
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :url, 'Image URL', class: "form-label"%>: 
          <%= form.text_field :url, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :price, 'Price', class: "form-label" %>: 
          <%= form.text_field :price, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :subject_id, 'Subject', class: "form-label" %>: 
          <%= form.collection_select :subject_id, @subjects, :id, :name, prompt: true, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :description, 'Description', class: "form-label"%>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <%= form.submit "Create", class: "btn btn-primary", style: "width: 100%;" %>
      <% end %>
    </div>

  </div>

  <div>
    <img src="https://www.shareicon.net/data/2015/08/15/85592_upload_512x512.png" style="width:200px; height:auto; object-fit:cover;">
  </div>

</div>

<p class="mt-5">
  Go Back: 
  <%= link_to ' Click me', books_list_path %>
</p>

app/views/books/show.html.erb
<div class="mt-3 px-5 container-fluid">

    <div class='d-flex gap-5'>
        <div>
            <h2 class="mb-3">Name: <%= @book.title  %></h2>
            <p class="mb-3"><strong>Price:</strong> <%= @book.price%></p>
            <p class="mb-3"><strong>Subject:</strong> <%= link_to @book.subject.name, "http://localhost:3000/books/show_subjects?id=#{subject.id}", class: "text-decoration-none"%></p>
            <p class="mb-3"><strong>Description:</strong> <br/> <%= @book.description%></p>
        </div>

        <div>
            <img src="<%= @book.url%>" style="height:350px; object-fit:cover;">
            <div class="d-flex gap-2 justify-content-between mt-2 px-1">
                <%= link_to 'Edit' , {action: 'edit', id: @book.id}, class: "btn btn-primary" %>
                <%= link_to 'Delete' , {action: 'delete', id: @book.id}, class: "btn btn-danger text-decoration-none" %>
            </div>
        </div>
    </div>

    <p class="mt-5">
        Go Back:
         <%= link_to 'to books list', books_list_path %>
    </p>
</div>

app/views/books/show_subjects.html.erb
<div class="mt-4 px-5 container-fluid">
    <h1 class="mb-5">Subject: <%= @subject.name -%></h1>

    <div class='d-flex justify-content-between align-items-center'>
        <h3> Books: </h3>
        <%= link_to 'Add Book' , books_new_path, class: " btn btn-primary text-decoration-none" %>
    </div>

    <div class='d-flex gap-5 mb-5 flex-wrap mt-3'>
        <% @subject.books.each do |book|%>

            <div class="card" style="width: 15rem;">
                <img src="<%= book.url%>" style="height:350px; object-fit:cover;" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to book.title, {action: "show", id: book.id}, class: "text-decoration-none"%>
                    </h5>
                    <p class="card-text">
                        <%= book.description%>
                    </p>
                    <div class="d-flex gap-2 justify-content-between mt-2 px-1">
                        <%= link_to 'Edit' , {action: 'edit', id: book.id}, class: "btn btn-primary" %>
                        <%= link_to 'Delete' , {action: 'delete', id: book.id}, class: "btn btn-danger text-decoration-none" %>
                    </div>
                </div>
            </div>

        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <!-- Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid px-5">
        <a class="navbar-brand" href="http://localhost:3000/subjects/list">Library</a>
        <div class="collapse navbar-collapse ps-5" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/subjects/list">Subjects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/books/list">Books</a>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    <!-- Nav Bar -->
    <%= yield %>
  </body>
</html>

app/views/subjects/list.html.erb
<!-- Banner Image -->
<div class="container-fluid d-flex align-items-start justify-content-center" 
    style="
        height: calc(100vh - 50px);
        background: url('https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');
        background-repeat: no-repeat;
        background-size: cover;"
    >
    <div class="px-5 py-3" style="background: #FFF; opacity: 0.9; margin-top: 200px;">
        <p style="font-size: 100px;">Subject List</p>
    </div>
</div>
<!-- Banner Image -->

<div class="mt-5 px-5 container-fluid">

    <div class='d-flex justify-content-between align-items-center'>
        <h2> Subjects: </h2>
        <%= link_to 'Add Subject' , subjects_new_path, class: " btn btn-primary text-decoration-none" %>
    </div>

    <div class='d-flex gap-5 mb-5 flex-wrap mt-3'>
        <% @subjects.each do |subject|%>
            <div class="card" style="width: 20rem;">
                <img src="<%= subject.url%>" style="height:350px; object-fit:cover;" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to subject.name, "http://localhost:3000/books/show_subjects?id=#{subject.id}", class: "text-decoration-none"  %>
                    </h5>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/subjects/new.html.erb
<div class="container-fluid p-5">
  <h2 class="mb-3">Add new Subject</h2>


  <div class="d-flex gap-5 align-items-center">

  <div>
    <div style="width:400px;">
      <%= form_with(model: @subject, url: subjects_create_path) do |form| %>
        <div class="mb-3">
            <%= form.label :name, 'Name: ', class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :url, 'Image URL: ', class: "form-label" %>
            <%= form.text_field :url, class: "form-control" %>
        </div>
        <%= form.submit "Create", class: "btn btn-primary", style: "width: 100%;" %>
      <% end %>
    </div>
  </div>

  <div>
    <img src="https://www.shareicon.net/data/2015/08/15/85592_upload_512x512.png" style="width:200px; height:auto; object-fit:cover;">
  </div>

  </div>
  
  <p class="mt-5">
    Go Back: 
    <%= link_to ' Click me', subjects_list_path %>
  </p>
</div>